server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/** # 路径匹配
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-payment
          uri: lb://service-payment
          predicates:
            - Path=/*/payment/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/*/order/**
        - id: service-item
          uri: lb://service-item
          predicates:
            - Path=/*/item/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/*/cart/**
        #==================web前端==========================
        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com
  redis:
    host: 106.14.242.86
    port: 16379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
auth:
  url: /trade.html,/pay.html,/myOrder.html,/order.html
login:
  url: http://passport.gmall.com/login.html?originUrl=
